version: "3.3"

services:
  ee:
    build: .
    restart: always
    command: python app.py "192.168.1.2" -U mqtt -p Jum747bo --interface=eno1 --time=15
    hostname: ee
    container_name: ee
    network_mode: host
    volumes:
      - ./app:/app
