version: "3.3"

services:
  ee:
    build: .
    restart: always
    hostname: ee
    command: python app.py "${MQTT_BROKER}" -U ${MQTT_USERNAME} -p ${MQTT_PASSWORD} --interface=eno1 --time=15
    container_name: ee
    network_mode: host
    volumes:
      - ./app:/app
